CREATE DATABASE IF NOT EXISTS FORGEIQ;
CREATE SCHEMA IF NOT EXISTS FORGEIQ.RAW;
CREATE SCHEMA IF NOT EXISTS FORGEIQ.CURATED;
CREATE SCHEMA IF NOT EXISTS FORGEIQ.ANALYTICS;FORGEIQ.PUBLIC.MY_PUBLIC_REPOFORGEIQ.PUBLIC.MY_PUBLIC_REPO
