CREATE TABLE IF NOT EXISTS FORGEIQ.RAW.ASSETS (
 ASSET_ID VARCHAR, ASSET_TYPE VARCHAR, LOCATION VARCHAR,
 IDEAL_VIBRATION FLOAT, IDEAL_TEMPERATURE FLOAT, IDEAL_RPM FLOAT,
 IDEAL_PRESSURE FLOAT, IDEAL_CURRENT FLOAT
);
CREATE TABLE IF NOT EXISTS FORGEIQ.RAW.FAILURES (
 FAILURE_ID VARCHAR, ASSET_ID VARCHAR, FAILURE_TIMESTAMP TIMESTAMP_NTZ,
 FAILURE_TYPE VARCHAR, ROOT_CAUSE VARCHAR, DOWNTIME_HOURS FLOAT, PRODUCTION_LOSS FLOAT
);
CREATE TABLE IF NOT EXISTS FORGEIQ.RAW.MAINTENANCE (
 WORK_ORDER_ID VARCHAR, ASSET_ID VARCHAR, MAINTENANCE_DATE TIMESTAMP_NTZ,
 MAINTENANCE_TYPE VARCHAR, FAILURE_TYPE VARCHAR, ROOT_CAUSE VARCHAR,
 DOWNTIME_HOURS FLOAT, MAINTENANCE_COST FLOAT, TECHNICIAN VARCHAR, RESOLUTION VARCHAR
);
CREATE TABLE IF NOT EXISTS FORGEIQ.RAW.SENSOR_TELEMETRY (
 EVENT_ID VARCHAR, EVENT_TIMESTAMP TIMESTAMP_NTZ, ASSET_ID VARCHAR,
 VIBRATION_MM_S FLOAT, TEMPERATURE_C FLOAT, RPM FLOAT,
 PRESSURE_BAR FLOAT, CURRENT_AMPS FLOAT
);
CREATE TABLE IF NOT EXISTS FORGEIQ.RAW.PRODUCTION (
 ORDER_ID VARCHAR, ASSET_ID VARCHAR, PRODUCTION_TIMESTAMP TIMESTAMP_NTZ,
 UNITS_PRODUCED FLOAT, GOOD_UNITS FLOAT, IDEAL_CYCLE_TIME_MIN FLOAT,
 PLANNED_PRODUCTION_TIME_MIN FLOAT, RUN_TIME_MIN FLOAT, DOWNTIME_MIN FLOAT
);

