CREATE OR REPLACE TABLE FORGEIQ.CURATED.SENSOR_TELEMETRY AS SELECT * FROM FORGEIQ.RAW.SENSOR_TELEMETRY;
CREATE OR REPLACE TABLE FORGEIQ.CURATED.FAILURES AS SELECT * FROM FORGEIQ.RAW.FAILURES;
CREATE OR REPLACE TABLE FORGEIQ.CURATED.MAINTENANCE AS SELECT * FROM FORGEIQ.RAW.MAINTENANCE;
CREATE OR REPLACE TABLE FORGEIQ.CURATED.PRODUCTION AS SELECT * FROM FORGEIQ.RAW.PRODUCTION;
