CREATE OR REPLACE VIEW FORGEIQ.ANALYTICS.ASSET_360 AS
SELECT a.*, COUNT(DISTINCT f.FAILURE_ID) PREVIOUS_FAILURE_COUNT,
       MAX(f.FAILURE_TIMESTAMP) LAST_FAILURE_TIMESTAMP,
       MAX(m.MAINTENANCE_DATE) LAST_MAINTENANCE_DATE
FROM FORGEIQ.RAW.ASSETS a
LEFT JOIN FORGEIQ.CURATED.FAILURES f ON f.ASSET_ID=a.ASSET_ID
LEFT JOIN FORGEIQ.CURATED.MAINTENANCE m ON m.ASSET_ID=a.ASSET_ID
GROUP BY ALL;


