CREATE OR REPLACE VIEW FORGEIQ.ANALYTICS.OEE AS
WITH x AS (
 SELECT ASSET_ID, DATE_TRUNC('HOUR',PRODUCTION_TIMESTAMP) HOUR,
 SUM(UNITS_PRODUCED) TOTAL_UNITS, SUM(GOOD_UNITS) GOOD_UNITS,
 SUM(IDEAL_CYCLE_TIME_MIN*UNITS_PRODUCED) IDEAL_TIME,
 SUM(RUN_TIME_MIN) RUN_TIME, SUM(PLANNED_PRODUCTION_TIME_MIN) PLANNED_TIME
 FROM FORGEIQ.CURATED.PRODUCTION GROUP BY 1,2
)
SELECT ASSET_ID,HOUR,
 CASE WHEN PLANNED_TIME>0 THEN LEAST(1,RUN_TIME/PLANNED_TIME) ELSE 0 END *
 CASE WHEN RUN_TIME>0 THEN LEAST(1,IDEAL_TIME/RUN_TIME) ELSE 0 END *
 CASE WHEN TOTAL_UNITS>0 THEN GOOD_UNITS/TOTAL_UNITS ELSE 0 END OEE
FROM x;


