CREATE OR REPLACE TABLE FORGEIQ.ANALYTICS.ML_FEATURES AS
WITH h AS (
 SELECT ASSET_ID,DATE_TRUNC('HOUR',EVENT_TIMESTAMP) HOUR,
 AVG(VIBRATION_MM_S) AVG_VIBRATION,STDDEV_POP(VIBRATION_MM_S) VIBRATION_STDDEV,
 AVG(TEMPERATURE_C) AVG_TEMPERATURE,MAX(TEMPERATURE_C) MAX_TEMPERATURE,
 AVG(RPM) AVG_RPM,STDDEV_POP(RPM) RPM_STDDEV,
 AVG(PRESSURE_BAR) AVG_PRESSURE,AVG(CURRENT_AMPS) AVG_CURRENT,MAX(CURRENT_AMPS) MAX_CURRENT
 FROM FORGEIQ.CURATED.SENSOR_TELEMETRY GROUP BY 1,2
), b AS (
 SELECT h.*,a.IDEAL_VIBRATION,a.IDEAL_TEMPERATURE,a.IDEAL_RPM,a.IDEAL_PRESSURE,a.IDEAL_CURRENT,
        a.LAST_MAINTENANCE_DATE,a.PREVIOUS_FAILURE_COUNT,
        LAG(AVG_VIBRATION) OVER(PARTITION BY h.ASSET_ID ORDER BY h.HOUR) PV,
        LAG(AVG_TEMPERATURE) OVER(PARTITION BY h.ASSET_ID ORDER BY h.HOUR) PT,
        LAG(AVG_RPM) OVER(PARTITION BY h.ASSET_ID ORDER BY h.HOUR) PR,
        LAG(AVG_PRESSURE) OVER(PARTITION BY h.ASSET_ID ORDER BY h.HOUR) PP,
        LAG(AVG_CURRENT) OVER(PARTITION BY h.ASSET_ID ORDER BY h.HOUR) PC
 FROM h JOIN FORGEIQ.ANALYTICS.ASSET_360 a USING(ASSET_ID)
)
SELECT b.*,
 AVG_VIBRATION-IDEAL_VIBRATION VIBRATION_DEVIATION,
 AVG_TEMPERATURE-IDEAL_TEMPERATURE TEMPERATURE_DEVIATION,
 AVG_RPM-IDEAL_RPM RPM_DEVIATION,
 AVG_PRESSURE-IDEAL_PRESSURE PRESSURE_DEVIATION,
 AVG_CURRENT-IDEAL_CURRENT CURRENT_DEVIATION,
 AVG_VIBRATION-PV VIBRATION_CHANGE_1H,
 AVG_TEMPERATURE-PT TEMPERATURE_CHANGE_1H,
 AVG_RPM-PR RPM_CHANGE_1H,
 AVG_PRESSURE-PP PRESSURE_CHANGE_1H,
 AVG_CURRENT-PC CURRENT_CHANGE_1H,
  DATEDIFF('HOUR',LAST_MAINTENANCE_DATE,b.HOUR) HOURS_SINCE_MAINTENANCE,
  AVG(AVG_VIBRATION) OVER(PARTITION BY b.ASSET_ID ORDER BY b.HOUR ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) VIBRATION_MEAN_3H,
  AVG(AVG_VIBRATION) OVER(PARTITION BY b.ASSET_ID ORDER BY b.HOUR ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) VIBRATION_MEAN_6H,
  AVG(AVG_TEMPERATURE) OVER(PARTITION BY b.ASSET_ID ORDER BY b.HOUR ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) TEMPERATURE_MEAN_3H,
  AVG(AVG_TEMPERATURE) OVER(PARTITION BY b.ASSET_ID ORDER BY b.HOUR ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) TEMPERATURE_MEAN_6H,
 o.OEE,
 IFF(EXISTS(SELECT 1 FROM FORGEIQ.CURATED.FAILURES f
           WHERE f.ASSET_ID=b.ASSET_ID AND f.FAILURE_TIMESTAMP>b.HOUR
             AND f.FAILURE_TIMESTAMP<=DATEADD('HOUR',6,b.HOUR)),1,0) FAILURE_NEXT_6H
FROM b LEFT JOIN FORGEIQ.ANALYTICS.OEE o ON o.ASSET_ID=b.ASSET_ID AND o.HOUR=b.HOUR;
