CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION FORGEIQ.ANALYTICS.FAILURE_PREDICTOR_V2 (
 INPUT_DATA => SYSTEM$REFERENCE('VIEW','FORGEIQ.ANALYTICS.ML_TRAIN_VIEW'),
 TARGET_COLNAME => 'FAILURE_NEXT_6H',
 CONFIG_OBJECT => {'ON_ERROR':'SKIP'}
);


