CREATE OR REPLACE VIEW FORGEIQ.ANALYTICS.FAILURE_RISK AS
SELECT
    ASSET_ID,
    HOUR AS EVENT_TIMESTAMP,
    PREDICTED_CLASS,
    FAILURE_PROBABILITY,
    CASE
        WHEN FAILURE_PROBABILITY >= 0.90 THEN 'CRITICAL'
        WHEN FAILURE_PROBABILITY >= 0.70 THEN 'HIGH'
        WHEN FAILURE_PROBABILITY >= 0.40 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_LEVEL
FROM FORGEIQ.ANALYTICS.PRODUCTION_PREDICTIONS;
