CREATE OR REPLACE VIEW FORGEIQ.ANALYTICS.COMMAND_CENTER_ALERTS AS
WITH alerts AS (
    SELECT ASSET_ID,EVENT_TIMESTAMP,FAILURE_PROBABILITY,RISK_LEVEL,PREDICTED_CLASS
    FROM FORGEIQ.ANALYTICS.FAILURE_RISK
    WHERE RISK_LEVEL IN ('MEDIUM','HIGH','CRITICAL')
    QUALIFY ROW_NUMBER() OVER(PARTITION BY ASSET_ID ORDER BY EVENT_TIMESTAMP DESC)=1
),
features AS (
    SELECT
        ASSET_ID,HOUR,
        AVG_VIBRATION,VIBRATION_STDDEV,VIBRATION_CHANGE_1H,VIBRATION_DEVIATION,
        AVG_TEMPERATURE,MAX_TEMPERATURE,TEMPERATURE_CHANGE_1H,TEMPERATURE_DEVIATION,
        AVG_RPM,RPM_STDDEV,RPM_CHANGE_1H,RPM_DEVIATION,
        AVG_PRESSURE,PRESSURE_CHANGE_1H,PRESSURE_DEVIATION,
        AVG_CURRENT,MAX_CURRENT,CURRENT_CHANGE_1H,CURRENT_DEVIATION,
        HOURS_SINCE_MAINTENANCE,PREVIOUS_FAILURE_COUNT,OEE
    FROM FORGEIQ.ANALYTICS.ML_FEATURES
),
e AS (
SELECT a.*,f.* EXCLUDE(ASSET_ID,HOUR),
    (CASE WHEN f.VIBRATION_DEVIATION>=1.5 THEN 3 WHEN f.VIBRATION_DEVIATION>=0.8 THEN 2 WHEN f.VIBRATION_DEVIATION>=0.4 THEN 1 ELSE 0 END
     +CASE WHEN f.VIBRATION_CHANGE_1H>=0.30 THEN 3 WHEN f.VIBRATION_CHANGE_1H>=0.15 THEN 2 WHEN f.VIBRATION_CHANGE_1H>=0.05 THEN 1 ELSE 0 END
     +CASE WHEN f.RPM_STDDEV>=10 THEN 1 ELSE 0 END) BEARING_SCORE,
    (CASE WHEN f.TEMPERATURE_DEVIATION>=20 THEN 3 WHEN f.TEMPERATURE_DEVIATION>=10 THEN 2 WHEN f.TEMPERATURE_DEVIATION>=5 THEN 1 ELSE 0 END
     +CASE WHEN f.TEMPERATURE_CHANGE_1H>=4 THEN 3 WHEN f.TEMPERATURE_CHANGE_1H>=2 THEN 2 WHEN f.TEMPERATURE_CHANGE_1H>=1 THEN 1 ELSE 0 END
     +CASE WHEN f.MAX_TEMPERATURE>=95 THEN 2 WHEN f.MAX_TEMPERATURE>=85 THEN 1 ELSE 0 END) MOTOR_SCORE,
    (CASE WHEN f.VIBRATION_DEVIATION>=1.5 THEN 2 WHEN f.VIBRATION_DEVIATION>=0.8 THEN 1 ELSE 0 END
     +CASE WHEN ABS(f.PRESSURE_DEVIATION)>=5 THEN 3 WHEN ABS(f.PRESSURE_DEVIATION)>=2 THEN 2 WHEN ABS(f.PRESSURE_DEVIATION)>=1 THEN 1 ELSE 0 END
     +CASE WHEN f.VIBRATION_CHANGE_1H>=0.30 THEN 2 WHEN f.VIBRATION_CHANGE_1H>=0.15 THEN 1 ELSE 0 END) PUMP_SCORE
FROM alerts a JOIN features f ON f.ASSET_ID=a.ASSET_ID AND f.HOUR=a.EVENT_TIMESTAMP
)
SELECT
    *,
    CASE
      WHEN ASSET_ID LIKE 'CNC-%' AND BEARING_SCORE>=3 THEN 'BEARING_DEGRADATION'
      WHEN ASSET_ID LIKE 'PRESS-%' AND MOTOR_SCORE>=3 THEN 'MOTOR_OVERHEATING'
      WHEN ASSET_ID LIKE 'PUMP-%' AND BEARING_SCORE>=3 THEN 'PUMP_DEGRADATION'
      WHEN MOTOR_SCORE>=BEARING_SCORE AND MOTOR_SCORE>=PUMP_SCORE AND MOTOR_SCORE>=3 THEN 'MOTOR_OVERHEATING'
      WHEN PUMP_SCORE>=BEARING_SCORE AND PUMP_SCORE>=MOTOR_SCORE AND PUMP_SCORE>=3 THEN 'PUMP_DEGRADATION'
      WHEN BEARING_SCORE>=3 THEN 'BEARING_DEGRADATION'
      ELSE 'EQUIPMENT_DEGRADATION'
    END LIKELY_FAILURE_TYPE,
    CASE
      WHEN ASSET_ID LIKE 'CNC-%' AND BEARING_SCORE>=3 THEN 'Inspect drive-end bearing, lubrication and shaft alignment'
      WHEN ASSET_ID LIKE 'PRESS-%' AND MOTOR_SCORE>=3 THEN 'Inspect motor cooling system, coolant flow and thermal load'
      WHEN ASSET_ID LIKE 'PUMP-%' AND BEARING_SCORE>=3 THEN 'Inspect pump impeller, seals, bearings and hydraulic performance'
      WHEN MOTOR_SCORE>=BEARING_SCORE AND MOTOR_SCORE>=PUMP_SCORE AND MOTOR_SCORE>=3 THEN 'Inspect motor cooling system and thermal load'
      WHEN PUMP_SCORE>=BEARING_SCORE AND PUMP_SCORE>=MOTOR_SCORE AND PUMP_SCORE>=3 THEN 'Inspect pump hydraulic system and impeller'
      ELSE 'Perform detailed equipment inspection'
    END RECOMMENDED_ACTION,
    CASE WHEN RISK_LEVEL='CRITICAL' THEN 'IMMEDIATE INSPECTION'
         WHEN RISK_LEVEL='HIGH' THEN 'SCHEDULE INSPECTION'
         ELSE 'MONITOR' END OPERATOR_ACTION
FROM e;
