CREATE OR REPLACE VIEW FORGEIQ.ANALYTICS.COMMAND_CENTER_RCA AS
SELECT
    ASSET_ID,EVENT_TIMESTAMP,FAILURE_PROBABILITY,RISK_LEVEL,
    LIKELY_FAILURE_TYPE,RECOMMENDED_ACTION,OEE,
    AVG_VIBRATION,VIBRATION_DEVIATION,VIBRATION_CHANGE_1H,
    AVG_TEMPERATURE,TEMPERATURE_DEVIATION,TEMPERATURE_CHANGE_1H,
    AVG_RPM,RPM_STDDEV,RPM_DEVIATION,
    AVG_PRESSURE,PRESSURE_DEVIATION,
    AVG_CURRENT,CURRENT_DEVIATION,
    HOURS_SINCE_MAINTENANCE,PREVIOUS_FAILURE_COUNT
FROM FORGEIQ.ANALYTICS.COMMAND_CENTER_ALERTS;
