CREATE TABLE IF NOT EXISTS FORGEIQ.ANALYTICS.WORK_ORDERS (
 WORK_ORDER_ID VARCHAR, ASSET_ID VARCHAR, CREATED_TIMESTAMP TIMESTAMP_NTZ,
 PRIORITY VARCHAR, FAILURE_PROBABILITY FLOAT, RISK_LEVEL VARCHAR,
 FAILURE_TYPE VARCHAR, RCA_EXPLANATION VARCHAR, RECOMMENDED_ACTION VARCHAR,
 ESTIMATED_DOWNTIME_HOURS FLOAT, ESTIMATED_PRODUCTION_LOSS FLOAT,
 STATUS VARCHAR, SOURCE VARCHAR
);

MERGE INTO FORGEIQ.ANALYTICS.WORK_ORDERS w
USING (
 SELECT ASSET_ID,EVENT_TIMESTAMP,FAILURE_PROBABILITY,RISK_LEVEL,
        LIKELY_FAILURE_TYPE FAILURE_TYPE,RCA_EXPLANATION,RECOMMENDED_ACTION,
        IFF(RISK_LEVEL='CRITICAL','CRITICAL','HIGH') PRIORITY,
        CASE WHEN LIKELY_FAILURE_TYPE='BEARING_DEGRADATION' THEN 14.0
             WHEN LIKELY_FAILURE_TYPE='MOTOR_OVERHEATING' THEN 8.0
             WHEN LIKELY_FAILURE_TYPE='PUMP_DEGRADATION' THEN 10.0 ELSE 8.0 END ESTIMATED_DOWNTIME_HOURS,
        CASE WHEN LIKELY_FAILURE_TYPE='BEARING_DEGRADATION' THEN 24500.0
             WHEN LIKELY_FAILURE_TYPE='MOTOR_OVERHEATING' THEN 9200.0
             WHEN LIKELY_FAILURE_TYPE='PUMP_DEGRADATION' THEN 5800.0 ELSE 5000.0 END ESTIMATED_PRODUCTION_LOSS
 FROM FORGEIQ.ANALYTICS.COMMAND_CENTER_RCA_RESULTS
) s
ON w.ASSET_ID=s.ASSET_ID AND w.FAILURE_TYPE=s.FAILURE_TYPE
AND w.STATUS IN ('OPEN','IN_PROGRESS')
WHEN NOT MATCHED THEN INSERT (
 WORK_ORDER_ID,ASSET_ID,CREATED_TIMESTAMP,PRIORITY,FAILURE_PROBABILITY,
 RISK_LEVEL,FAILURE_TYPE,RCA_EXPLANATION,RECOMMENDED_ACTION,
 ESTIMATED_DOWNTIME_HOURS,ESTIMATED_PRODUCTION_LOSS,STATUS,SOURCE
) VALUES (
 'WO-'||UUID_STRING(),s.ASSET_ID,s.EVENT_TIMESTAMP,s.PRIORITY,
 s.FAILURE_PROBABILITY,s.RISK_LEVEL,s.FAILURE_TYPE,s.RCA_EXPLANATION,
 s.RECOMMENDED_ACTION,s.ESTIMATED_DOWNTIME_HOURS,s.ESTIMATED_PRODUCTION_LOSS,
 'OPEN','FORGEIQ_COMMAND_CENTER'
);
