CREATE OR REPLACE VIEW FORGEIQ.ANALYTICS.COMMAND_CENTER AS
SELECT
 a.ASSET_ID,a.EVENT_TIMESTAMP,a.FAILURE_PROBABILITY,a.RISK_LEVEL,
 a.LIKELY_FAILURE_TYPE,
 a.AVG_VIBRATION,a.VIBRATION_DEVIATION,a.VIBRATION_CHANGE_1H,
 a.AVG_TEMPERATURE,a.TEMPERATURE_DEVIATION,a.TEMPERATURE_CHANGE_1H,
 a.AVG_RPM,a.RPM_STDDEV,a.RPM_DEVIATION,a.RPM_CHANGE_1H,
 a.AVG_PRESSURE,a.PRESSURE_DEVIATION,a.PRESSURE_CHANGE_1H,
 a.AVG_CURRENT,a.CURRENT_DEVIATION,a.CURRENT_CHANGE_1H,
 a.HOURS_SINCE_MAINTENANCE,a.PREVIOUS_FAILURE_COUNT,a.OEE,
 a.RECOMMENDED_ACTION,a.OPERATOR_ACTION,
 r.RCA_EXPLANATION,
 w.WORK_ORDER_ID,w.STATUS WORK_ORDER_STATUS,w.PRIORITY WORK_ORDER_PRIORITY,
 w.ESTIMATED_DOWNTIME_HOURS,w.ESTIMATED_PRODUCTION_LOSS
FROM FORGEIQ.ANALYTICS.COMMAND_CENTER_ALERTS a
LEFT JOIN FORGEIQ.ANALYTICS.COMMAND_CENTER_RCA_RESULTS r
 ON r.ASSET_ID=a.ASSET_ID AND r.EVENT_TIMESTAMP=a.EVENT_TIMESTAMP
LEFT JOIN FORGEIQ.ANALYTICS.WORK_ORDERS w
 ON w.ASSET_ID=a.ASSET_ID
 AND w.FAILURE_TYPE=a.LIKELY_FAILURE_TYPE
 AND w.STATUS IN ('OPEN','IN_PROGRESS');
